### ISSUE TITLE
Unusual/non-standard require

### ISSUE THREAD

**Issue by ioquatix** [kramdown/parser-gfm#12]
Normally when you have a gem with a name like `kramdown-parser-gfm`, you'd expect to write `require 'kramdown/parser/gfm'`. Is there some reason for going against this standard?

**Comment by ashmaroli** [comment]
@ioquatix Both should work equally fine.
Does `require 'kramdown/parser/gfm'` not work for you?

**Comment by ioquatix** [comment]
After I looked at the code, I figured out it would work, which is good, and yes it does work.

I think that's what should be recommended in the README too. But, it's up to you.
