### ISSUE TITLE
header with m=5 test fails

### ISSUE THREAD

**Issue by boutil** [kramdown/parser-gfm#19]
Trying to run the tests from a fresh cloned repository, I get the following error:

```
 gfm header ids to html
      --- expected
      +++ actual
      @@ -24,5 +24,5 @@
       
       <h3 id=\"with--typographic--symbols\">with — « typographic » … symbols</h3>
       
      -<h3 id=\"with-m5\">with <script type=\"math/tex\">m=5</script></h3>
      +<h3 id=\"with-m5\">with \\(m=5\\)</h3>
       "
```
I could not find the part of kramdown which is supposed to create the <script type="math/tex"> part
I am using kramdown v2.3 on Debian.

**Comment by gettalong** [comment]
There was a MathJax related change in [2.2.0](https://kramdown.gettalong.org/news.html#kramdown-220-released), so you need to adjust the tests.
