### ISSUE TITLE
[Style] Enforce use of Rocket syntax in hashes

### ISSUE THREAD

**Issue by ashmaroli** [kramdown/parser-gfm#2]
I would recommend the use of older rocket syntax in hashes because:
- it mirrors the output from Ruby
  ```ruby
  gamma = { foo: 'bar' }
  delta = { :foo => 'bar' }

  puts gamma  # => {:foo=>"bar"}
  puts delta  # => {:foo=>"bar"}
  ```
- it allows aligning keys for improving readability
  ```ruby
  a = {
    :name    => 'John Doe',
    :age     => 35,
    :address => '122B, Baker Street'
  }

  b = {
    name: 'John Doe',  # name   : 'John Doe' would raise a syntax error
    age: 35,
    address: '122B, Baker Street'
  }
  ```
- Does not *resemble* JSON:
  ```ruby
  payload = {
    "name": "John Doe",
    "age": "35",
    "address": "122B, Baker Street"
  }

  puts payload # => {:name=>"John Doe", :age=>"35", :address=>"122B, Baker Street"}

**Comment by gettalong** [comment]
My 2c:

* I actually prefer the new syntax.
* Aligning is still possible using whitespace.
* Why would anyone think they are writing in *Javascript*ON if they are in a Ruby file?

These aside once kramdown 2.0 is released, this repo becomes unmaintained and a new maintainer can modify it to their heart's content :smile:

**Comment by ashmaroli** [comment]
I don't mind taking over when you step down.
It is a very small project.
