### ISSUE TITLE
Parser doesn't process markdown nested inside of HTML tags

### ISSUE THREAD

**Issue by charlottetan** [kramdown/parser-gfm#28]
For the following code snippet:
```
<div dir="rtl">
## توافقنامه‌ی مجوز همکاری

مشارکت در این مخزن به معنی موافقت شما با مجوز [LICENSE](/blob/master/LICENSE) این مخزن است.
</div>
```

The expected HTML to be rendered is:
```
<div dir="rtl">
    <h2>توافقنامه‌ی مجوز همکاری</h2>
    <p>مشارکت در این مخزن به معنی موافقت شما با مجوز <a href="blob/master/LICENSE">LICENSE</a> این مخزن است.</p>
</div>
```

And GFM renders that perfectly:
https://github.com/EbookFoundation/free-programming-books/blob/e629db6b05a72fd64a6b33feeeebbe830641cf10/CONTRIBUTING-fa_IR.md
<img src="https://user-images.githubusercontent.com/4824630/135773203-12bd9a97-ce99-45d3-a097-5d7de249b7f6.png" width="50%">

However kramdown-parser-gfm appears to stop processing any markdown once it is nested under an HTML tag
https://ebookfoundation.github.io/free-programming-books/CONTRIBUTING-fa_IR.html
<img src="https://user-images.githubusercontent.com/4824630/135773247-92c361d0-7f99-47d9-8a2a-aa1a8a4308a3.png" width="50%">

See https://github.com/EbookFoundation/free-programming-books/issues/5559 for more information

**Comment by ashmaroli** [comment]
You need to add `markdown="1"` attribute to the HTML block tag:
```
<div markdown="1">
  ## Heading 2
</div>
```

**Comment by davorpa** [comment]
> You need to add `markdown="1"` attribute to the HTML block tag:
> 
> ```
> <div markdown="1">
>   ## Heading 2
> </div>
> ```

Thanks for the tip :hugs:. We tried it to see what happens.

**Comment by charlottetan** [comment]
Thanks so much for the explanation! I tried adding `markdown="1"` and for the most part it worked fine, but it seems that standalone URLs aren't parsed, am I missing something?

#### For example, given code:
```
<div dir="rtl" markdown="1">
این مرامنامه از این جا گرفته شده است: [Contributor Covenant][homepage],
نسخه‌ی 1.3.0 در این جا در دسترس است: https://contributor-covenant.org/version/1/3/0/

[homepage]: https://contributor-covenant.org
</div>
```

#### Expected HTML:
```
<p dir="auto">این مرامنامه از این جا گرفته شده است: <a href="https://contributor-covenant.org" rel="nofollow">Contributor Covenant</a>,
نسخه‌ی 1.3.0 در این جا در دسترس است: <a href="https://contributor-covenant.org/version/1/3/0/" rel="nofollow">https://contributor-covenant.org/version/1/3/0/</a></p>
```
Expected screenshot:
![image](https://user-images.githubusercontent.com/4824630/150668510-a57d4389-4649-404f-beb5-1b1add8a5708.png)


#### Actual HTML:
```
<p>این مرامنامه از این جا گرفته شده است: <a href="https://contributor-covenant.org">Contributor Covenant</a>,
نسخه‌ی 1.3.0 در این جا در دسترس است: https://contributor-covenant.org/version/1/3/0/</p>
```
Actual screenshot:
![image](https://user-images.githubusercontent.com/4824630/150668522-d71bb409-67cb-421b-ac16-8a3aed97e7f6.png)

**Comment by ashmaroli** [comment]
@gettalong Please look into https://github.com/kramdown/parser-gfm/issues/28#issuecomment-1019429480
It's beyond my understanding of the codebase.
Thanks.

**Comment by gettalong** [comment]
@ashmaroli @charlottetan If you don't use the `<div>` tag around, it also won't work. So I don't think using plain URLs is supported at all. I didn't find anything in the code, either.

Is there any example where using a plain URL without enclosing angle brackets works?

**Comment by charlottetan** [comment]
> #### Expected HTML:
> ```
> <p dir="auto">این مرامنامه از این جا گرفته شده است: <a href="https://contributor-covenant.org" rel="nofollow">Contributor Covenant</a>,
> نسخه‌ی 1.3.0 در این جا در دسترس است: <a href="https://contributor-covenant.org/version/1/3/0/" rel="nofollow">https://contributor-covenant.org/version/1/3/0/</a></p>
> ```
> 
> Expected screenshot: ![image](https://user-images.githubusercontent.com/4824630/150668510-a57d4389-4649-404f-beb5-1b1add8a5708.png)
>

Using plain URLs works in Github's default readme, for example, see this file on this branch:
https://github.com/charlottetan/free-programming-books/blob/main/docs/CODE_OF_CONDUCT-fa_IR.md

**Comment by gettalong** [comment]
@charlottetan I meant an example where this works with kramdown and parser-gfm.

**Comment by charlottetan** [comment]
I'm confused, plain URLs work in Github's readme pages, are plain URLs not expected to work with kramdown+parser-gfm?

**Comment by gettalong** [comment]
parser-gfm doesn't use the parser from Github but a custom implementation. So it is not 100% compatible with GFM and this is a feature that is not yet implemented.

**Comment by ashmaroli** [comment]
> this is a feature that is not yet implemented.

Thank you @gettalong

@charlottetan Until this feature gets implemented, (maybe, maybe not..), you may instruct kramdown to parse your standalone URLs and render them as links by surrounding each URL in angle brackets (`<`, `>`).
For example:

```
نسخه‌ی 1.3.0 در این جا در دسترس است: <https://contributor-covenant.org/version/1/3/0/>
```

**Comment by charlottetan** [comment]
Looks like there's already a feature request for that with #17. 
Thanks so much @gettalong and @ashmaroli!
