### ISSUE TITLE
GFM strikethrough seemingly broken when there's only one character inside

### ISSUE THREAD

**Issue by taoky** [kramdown/parser-gfm#8]
(Transferred from [Kramdown Issue 539](https://github.com/gettalong/kramdown/issues/539))

The syntax `~~content~~` does not seem to work when "content" is only one character. But the GFM actually supports it like this:

~~a~~

I'm not familiar with ruby, and fail in configuring with kramdown 2.0.0.beta2 with GFM parser. So I manually modified the test in `strikethrough.text` and `strikethrough.html`.

`strikethrough.text` adds `~~a~~`, and `strikethrough.html` adds `<p><del>a</del></p>`, then run `rake test`, and I get the output:

```
2) Failure:
TestFiles#test_gfm_/home/tao/sandbox/parser-gfm/test/testcases/strikethrough_text_to_html [/home/tao/sandbox/parser-gfm/test/test_files.rb:32]:
--- expected
+++ actual
@@ -1,6 +1,6 @@
 "<p><del>This is a test</del></p>
 
-<p><del>a</del></p>
+<p>~~a~~</p>
 
 <p>~<del>This is another test</del>~</p>
 

```

It means this bug still exists in parser-gfm.

**Comment by ashmaroli** [comment]
I've a fix ready locally. Will submit a PR once this repo has Travis CI wired up
(requires kramdown-2.0 to be shipped to avoid code-churn here)

**Comment by gettalong** [comment]
@ashmaroli kramdown 2.0.0 has been released
